# Generated by Django 5.2.17 on 2026-09-30 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="nom")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Ex : Boubou, Costume, Caftan, Robe…",
                        max_length=80,
                        verbose_name="type de tenue",
                    ),
                ),
                (
                    "fabric",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="type de tissu"
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="prix (FCFA)")),
                (
                    "sizes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex : ["S", "M", "L"]',
                        verbose_name="tailles",
                    ),
                ),
                (
                    "colors",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='Ex : [{"name": "Bleu nuit", "hex": "#1b2a49"}]',
                        verbose_name="couleurs disponibles",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Disponible"), ("sold_out", "Épuisé")],
                        db_index=True,
                        default="available",
                        max_length=12,
                        verbose_name="statut",
                    ),
                ),
                (
                    "is_favorite",
                    models.BooleanField(
                        db_index=True, default=False, verbose_name="coup de cœur"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="créée le"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="modifiée le"),
                ),
            ],
            options={
                "verbose_name": "tenue",
                "verbose_name_plural": "tenues",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TenueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="bakhyaye/tenues", verbose_name="image"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "tenue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shop.tenue",
                    ),
                ),
            ],
            options={
                "verbose_name": "image",
                "verbose_name_plural": "images",
                "ordering": ["position", "id"],
            },
        ),
    ]
